name: 'Jaimin-Patel30-NoteDown'
description: 'Note Down the record into dynamodb'
branding:
  icon: 'book'  
  color: 'purple'
inputs:
  key:
    description: 'AWS account key'
    required: true
  secret:
    description: 'AWS account secret'
    required: true
  repository:
    description: 'repository name as label in table'
    required: true
outputs:
  time: # output will be available to future steps 
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
