name: 'NoteDown'
description: 'Note Down the record into dynamodb'
inputs:
  milliseconds:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: '1000'
outputs:
  time: # output will be available to future steps 
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
